### PR TITLE
Split fish_prompt into two seperate functions

### LINKED ISSUE #49: Work around native fish prompt for long filepaths
Hey,

I just switched to fish and ran into the issue of it changing my prompt to `>` if the line is really long. This behavior is documented here: https://github.com/fish-shell/fish-shell/issues/904.

As *pure* is a two line prompt, this behavior is not needed. Apparently one can work around this issue by wrapping the first line in a `--on-event fish_prompt` function, as suggested here: https://github.com/fish-shell/fish-shell/issues/904#issuecomment-290882082.

Would it be possible to adjust *pure* accordingly?

Thanks

### PR DESCRIPTION
**Pull request by pierrebeaucamp**
Renders the first line of the prompt in a separate function. This
prevents fish from thinking that the prompt is too wide for the screen.
See fish-shell/fish-shell#904. Fixes #49.

### CODE REVIEW

**Comment by edouard-lopez** [comment]
bump

**Comment by pierrebeaucamp** [comment]
This should be good to go, however I couldn't test the virtualenv prefix yet (Mainly because I don't work with python and thought it would be trivial for someone else to check if the feature is still working).

**Comment by mortenvn** [comment]
I just tested the virtualenv and it still works fine :)

screen shot 2017-11-28 at 21 17 28

**Comment by pierrebeaucamp** [comment]
I don't know if anyone expects me to push the 'merge' button (as I recently got write access to this repo). I'd be more comfortable if @rafaelrinaldi could do that 😃

**Comment by edouard-lopez** [comment]
We need to start adding some tests to our project so we are more comfortable merging PR. We allready have a [discussion about testing](https://github.com/rafaelrinaldi/pure/issues/35).

I'm merging has we have several review on this one 🤞

**Pull request merged**
