### PR TITLE
Add username and host to prompt in SSH sessions

### PR DESCRIPTION
**Pull request by benedictleejh**
It doesn't follow how the original pure for ZSH does it, but I find having it first thing in the prompt makes it more obvious that you're in an SSH session.

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
Thanks for your PR!

I understand this behaves the way you expect. However we aim to be a consistent port from the original implementation. If you can do it in a way that you can tweak via variables to fit your needs instead of it being the default otherwise. You think that's doable?

**Comment by benedictleejh** [comment]
The colours of the host and username can be easily modified to be tweakable using variables.

The location is doable as well, I feel, though the implementation might not be as nice as the colour modification.

**Comment by benedictleejh** [comment]
I cannot remember if GitHub sends notifications about updates to pull requests, so a quick ping from me.

I've used variables to colour the username and hostname. There's also a variable explicitly for root, since root is supposed to be coloured differently in the original pure.

Also, there's a variable to set where to show the information (at the start, or end), defaulting to the original pure prompt's location.

**Comment by rafaelrinaldi** [comment]
@benedictleejh This looks pretty cool! Thanks for putting some effort into it.

May I ask you a few things?

1. Can you update the `README.md` file to list SSH support to our features list?
2. Can you please provide a screenshot of before/after your changes and, if possible, a screenshot of how the ZSH plugin behaves?

Other than that it looks good to me. I will just wait for at least one more reviewer to chime in as we always do 👍

**Comment by benedictleejh** [comment]
Alright, I've updated the `README.md` to list SSH support in the features. I've also added the configurable options for SSH support in the `README` as well.

Screenshots of behaviour:

pure-fish before
pure-before

pure-fish after, user
pure-after

pure-fish after, root
pure-after-root

pure-zsh, user
pure-zsh-ssh

pure-zsh, root
pure-zsh-root

I've tested with fish 2.5.0, and it doesn't seem to be having any issues. Those screenshots were taken with fish 2.5.0.

**Comment by rafaelrinaldi** [comment]
@benedictleejh Thanks a lot for taking the time to do this! Looks great to me, will give the collaborators some time to hear what them have to say 👍

**Comment by benedictleejh** [comment]
I've taken the liberty of fixing the merge conflicts with the current master.

According to pure-zsh, the command duration comes after the user and hostname, so I've done that.

pure-zsh
zsh-pure-host-cmd-dur

pure-fish
pure-fish-cmddur-ssh

**Comment by rafaelrinaldi** [comment]
@benedictleejh Thanks a lot! I will merge this PR.

**Pull request merged**
