### PR TITLE
Fix iTerm shell integration

### PR DESCRIPTION
**Pull request by schrodincat**
Fixes https://github.com/rafaelrinaldi/pure/issues/116

### CODE REVIEW

**Comment by edouard-lopez** [comment]
could you add a `tests/fish_mode_prompt.test.fish` that assert:
* [`$status` is `0`](https://github.com/rafaelrinaldi/pure/blob/9a1aa01b57c0c46f3cad2cc59217117ae8203ac6/tests/fish_right_prompt.test.fish#L5-L7)
* [output is empty](https://github.com/rafaelrinaldi/pure/blob/9a1aa01b57c0c46f3cad2cc59217117ae8203ac6/tests/_pure_prompt_vimode.test.fish#L5-L7)

**Comment by schrodincat** [comment]
@edouard-lopez I have no idea why tests are failing, can you look into that?

**Comment by edouard-lopez** [comment]
@schrodincat 

`fish_mode_prompt` doesn't print any so there is no string to compare, 
but we can check the output has no length.

But I think there are problems with other tests.

**Comment by schrodincat** [comment]
> fish_mode_prompt doesn't print any so there is no string to compare, but we can check the output has no length

Yep, I came to the same conclusion.

**Pull request merged**
