### PR TITLE
Pull request for allow-dynamic-fish_right_prompt-value

### PR DESCRIPTION
**Pull request by edouard-lopez**
**related:** #186 

---
# v3.0.0: Support dynamic content for right prompt

## :bomb:  Breaking Change

`pure_right_prompt` is now a function so its value can be re-evaluated on each rendering.

	function pure_right_prompt
	end

Some examples are available in [fish_right_prompt.test.fish](https://github.com/rafaelrinaldi/pure/blob/8fd5d2fd466fba977017e8174cad86f16884eeff/tests/fish_right_prompt.test.fish).

:information_source:: This is considered a major updated as we change the existing configuration API.

---

### Todo:

* [x] create `3.0.0` release note based on this content
* [ ] merge
* [ ] tag `bump to 3.0.0` commit as `v3.0.0` (can be done by github on merge?)
* [ ] communicate

### CODE REVIEW

**Comment by filipebarros** [comment]
@edouard-lopez does it mean that instead of using
```
set pure_right_prompt 'something'
```

now this needs to be set as:

```
function pure_right_prompt
    something
end
```
?

**Comment by edouard-lopez** [comment]
@filipebarros once it's merged, yes. That's the only way I was able to re-evaluate the value.

**Comment by filipebarros** [comment]
Should that be part of the readme?

**Comment by edouard-lopez** [comment]
@filipebarros you are absolutely correct, readme need to be updated

**Comment by edouard-lopez** [comment]
Excellent point, I got carried away while trying to fix this but kept a weird feeling about it.
I will update, in coming days, the PR to remove the variable entirely and fall back to native behaviour.

**Comment by filipebarros** [comment]
@edouard-lopez @schrodincat any eta on this feature being merged?

**Comment by filipebarros** [comment]
🏓

**Comment by schrodincat** [comment]
>🏓 

@filipebarros sorry for the delay😓, I’ll update the PR tomorrow🤝

**Pull request merged**
