### PR TITLE
feature single line prompt

### LINKED ISSUE #65: Option to make prompt 1 line
Is it possible to have an option to be like this? https://github.com/DFurnes/purer.

### PR DESCRIPTION
**Pull request by edouard-lopez**
fixes #65

| Option                                         | Default | Description                                                                                     |
| :--------------------------------------------- | :------ | :---------------------------------------------------------------------------------------------- |
| **`pure_enable_single_line_prompt`**                        | `false` | `true`: Compact prompt as a single line |

### Preview

> feature-pure_enable_single_line_prompt

### CODE REVIEW

**Comment by edouard-lopez** [comment]
@jorgebucaran could you have a look at the tests, I can't figure out why they are failing? 

Behaviour is hectic, I try to purge variables before each test, but doesn't seem to work. I might be missing something

**Comment by jorgebucaran** [comment]
@edouard-lopez I'm currently rewriting Fishtape, so maybe after that! 👍

**Comment by edouard-lopez** [comment]
I'm having pretty weird behavior with [`fishtape`+`pure`+`githubCI`](https://github.com/rafaelrinaldi/pure/pull/265/checks): `@msg` do not show up

It works locally, I'm wondering if coloring is a problem here as I call them like

```fish
@mesg (_print_filename $current_filename)
```

with _print_filename defined like:
```fish
function _print_filename --argument-names filename
    echo (set_color cyan)$filename(set_color normal)
end
```

**Comment by jorgebucaran** [comment]
TAP is a text-only format, so you shouldn't use color.

**Pull request merged**
