### PR TITLE
Remove useless fish shebang.

### PR DESCRIPTION
**Pull request by bucaran**
- [x] Reviewed by @rafaelrinaldi
- [x] Reviewed by @edouard-lopez 

---

All the files included in this prompt have a *.fish* extension and none of them is meant to be used as a "system command".

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@bucaran Thanks for your contribution!
@edouard-lopez Can you please just test this and see everything is :+1:? I'm not at a computer right now.

**Comment by bucaran** [comment]
Sure, let me check again!

**Comment by rafaelrinaldi** [comment]
@bucaran No worries, all good from your side. I was talking to Edouard. We never merge anything before both of us review it (even docs) :wink:

**Comment by edouard-lopez** [comment]
Good for me too

**Comment by bucaran** [comment]
Thanks!

**Pull request merged**
