### PR TITLE
Fix: test returned eval errors

### LINKED ISSUE #38: Broken after fish update?
Just updated fish to `2.5.0` today and it seems like prompt is broken (yup, it's me again!). This is what I get:

```
test returned eval errors:
        invalid integer ''
test returned eval errors:
        invalid integer ''
~ 
❯ 
```

Anyone else experiencing the same issue?

### PR DESCRIPTION
**Pull request by ponko2**
fix #38

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
That was fast! Thanks for your PR.

@oranja @edouard-lopez I'm gonna merge and release it as `v1.0.1` tonight 👍

**Comment by james2doyle** [comment]
Awesome! Just switched to default until this fix is released.

**Comment by rafaelrinaldi** [comment]
@james2doyle [Just published the new release](https://github.com/rafaelrinaldi/pure/releases/tag/v1.0.1), sorry for the delay.

@ponko2 Thanks again for your PR 👍

**Comment by james2doyle** [comment]
Just updated. Works wonderfully. Thanks!

**Comment by rafaelrinaldi** [comment]
@james2doyle Just pushed a new version with tweaks: https://github.com/rafaelrinaldi/pure/releases/tag/v1.1.0

**Pull request merged**
