### PR TITLE
Note workaround in README for Oh My Fish users

### PR DESCRIPTION
**Pull request by benedictleejh**
Add a note in the README for Oh My Fish users that explains how to workaround Oh My Fish not supporting `conf.d` snippets currently

### CODE REVIEW

**Comment by edouard-lopez** [comment]
Thanks @benedictleejh 

@rafaelrinaldi I would prefer to keep the readme as simple as possible, could you enable the `wiki` for the project so we can put the detailed explanation there and only keep the command line?

I'm reducing the PR to the command to execute and a link to the wiki page

The wiki page could contains :

### Oh-My-Fish not currently supporting `conf.d` snippets in plugins and themes

> Due to Oh My Fish not currently supporting `conf.d` snippets in plugins and themes (oh-my-fish/oh-my-fish#646),
> an additional step to add the snippets to fish's `conf.d` is needed to have the prompt work correctly.
> 
> ```fish
> omf install pure
> ln -s $OMF_PATH/themes/pure/conf.d/pure.fish ~/.config/fish/conf.d/pure.fish
> ```
> 
> **Note**: Use `$XDG_CONFIG_HOME/fish` to find the path to your fish configuration directory if the `XDG_CONFIG_HOME` environment variable is set on your system.

**Comment by derekstavis** [comment]
This should be now fixed by oh-my-fish/oh-my-fish#653. To test it, use the omf dev channel (see omf help on how to switch channels).

**Comment by edouard-lopez** [comment]
Thanks @derekstavis for the update.

@benedictleejh would you mind testing the dev channel feature against your issue?

**Comment by benedictleejh** [comment]
I've switched to the dev channel to test, but it doesn't solve the issue. My suspicion is that the new `conf.d` loading in Oh-My-Fish only works with plugins, and not themes, because themes are handled differently from packages. I haven't had the time to test against a plugin using `conf.d` yet.

**Comment by edouard-lopez** [comment]
@benedictleejh Thanks for the quick feedback :+1: 

@rafaelrinaldi could you open the wiki [as described in my first comment](#issuecomment-436980699)?

**Pull request merged**
