### PR TITLE
Screenshots

### PR DESCRIPTION
**Pull request by edouard-lopez**
**related:** #113 

---

I used [shutter](http://shutter-project.org) to take screenshots the content of the window then generated the window's decorations and shadow with [Screely](https://www.screely.com/).

<div align=center>
Pure with dark colorscheme
Pure with light colorscheme
</div>

### Build screenshot context

Colorscheme come from [chriskempson/base16](https://github.com/chriskempson/base16) thanks to [smh/base16-shell-fish](https://github.com/smh/base16-shell-fish) plugin. You can use whatever scheme name from the [Scheme Repositories' section](https://github.com/chriskempson/base16#scheme-repositories)

### Light
```fish
set colorscheme classic-light 
source ./tools/screenshots.fish 
```

### Dark
```fish
set colorscheme classic-dark 
source ./tools/screenshots.fish 
```

### Write command

I used the following
```fish
sleep 6s; false
```
```fish
cd $HOME/.dev/pure
```
```fish
git reset HEAD~1
```

### CODE REVIEW

**Comment by edouard-lopez** [comment]
@rafaelrinaldi Sure, thanks :)

**Comment by schrodincat** [comment]
> I used shutter to take screenshots the content of the window then generated the window's decorations and shadow with Screely.

I can take screenshots with Hyper on macOS. I mean I hate Hyper, but it looks pretty, you cannot deny that😏

**Comment by edouard-lopez** [comment]
Whatever like best :+1:

**Comment by schrodincat** [comment]
screenshot 2019-01-15 at 18 09 36
screenshot 2019-01-15 at 18 12 03

**Comment by rafaelrinaldi** [comment]
Beautiful @schrodincat! It looks perfect on retina. I'm good with these.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi could you approve this PR, we require at least one (I though dismissing it would work. 

Did you set new rules for PRs?

**Comment by schrodincat** [comment]
> What is retina's screen resolution?

@edouard-lopez you mean display? I'm on 5K iMac which is 5120 x 2880. I don't think it matters though, retina is just doubles pixels in both axis, so screenshots of the app should look the same on any retina Mac regardless of the overall screen resolution.

**Pull request merged**
