### PR TITLE
A complete Fish installer for pure

### PR DESCRIPTION
**Pull request by oranja**
Check this out. (in regard to #9)
Instructions (after merge to 'master'):
```fish
curl -Ls https://raw.github.com/rafaelrinaldi/pure/master/installer.fish > pure_installer.fish
and source ./pure_installer; and install_pure
````

On a personal note: this was not fun. letting the framework do all the dirty stuff for you is so much better.

_Edit_: Below are a few of the problems I ran into on the way:

1. Making the `installer.fish` executable and running it with `#/usr/bin/env fish` at the top starts a new Fish shell. Any changes to `fish_function_path` from within that shell are not propagated back up to the original shell process.
2. `set -l fish_function_path (echo $HOME/.config/fish/functions) $fish_function_path` doesn't do much. `$HOME/.config/fish/functions` is already the first entry in `fish_function_path` AFAIK. Also, sub-directories are not read automatically. Perhaps you meant to add the `theme_pure` folder? That would make more sense, but it's better not rely on the user running the installer from `~/.config/fish/functions` or any other specific place.
3. There's no need to source the internal function files if their path is already in `fish_function_path`. Fish will find the files and the functions when they are needed.
4. Sourcing `fish_prompt.fish` once applies the theme in the current shell, but doesn't persist it with future shells. `fish_prompt.fish` must be in some directory that Fish looks for functions in.
5. btw, why `printf` with `\n` on every output and not just use `echo`?

@edouard-lopez I hope that not getting it to work on the first time doesn't take from your motivation to do more with Fish. This is probably not 100% correct either, and I'm not a great Fish expert, but if you have any questions or want to solve any more "cases" together, I'd be happy to lend a hand.
:beers:

### CODE REVIEW

**Comment by edouard-lopez** [comment]
No worries, I'm fully aware that I'm not fluent in Fish yet.

1. did know about the shebang behavior, it does explain some behavior. Is it true for others shells?
2. I started from the original 3-liners and wasn't sure either about the `set -l fish_function_path …` ;
3. good to know (my background in fish is recent) ;
4. ok
5. just an habit, it's more explicit than `echo` and has richer formatting capabilities.

Why did you unwrap the `function`? Having no funtion or a scope too wide will cause troubles and floating code will be more difficult to refactor.

**Comment by oranja** [comment]
> Why did you unwrap the function? Having no funtion or a scope too wide will cause troubles and floating code will be more difficult to refactor.

1) Every function you declare will stay in Fish's "global" functions for the lifetime of the shell session. I'm not saying it's bad to declare functions, but you might want to "namespace" them. So `fetch_source` becomes `pure::fetch_source` or `pure.fetch_source`. It's also an option to remove one-time functions at the end (`functions --erase <function_name>`). Whether you keep the functions or erase them, namespacing is a good idea.
2) Fish function scopes are happy to shadow outer scopes, so that to get access to variables from outside, you need to use `--inherit-variable <var>` (or `-V <var>`) in the function's "signature".
3) I just found it more comfortable for me to see the installation steps as they come when it's all flat.

p.s.
I'm not sure about other shells' behavior when the script begins with a shebang. My guess is that there is a way to get back variables declared in subshells, but that by default they are not propagated automatically to the parent shell.

**Comment by edouard-lopez** [comment]
Thanks for all the detail.

I agree with your 3rd point, hence the [first function](https://github.com/rafaelrinaldi/pure/blob/388dbad43cac932a87d1d159fc2169311e64c723/installer.fish#L3) which give a keep overview of what happen. You can literally read it like an ordered list:

```
function install
    check_git_is_present
    fetch_source
    enable_theme
end
```

I will rebase on top of your code and PR when done and close all related issue then.

**Comment by rafaelrinaldi** [comment]
@oranja thanks for the PR! I only had the chance to take a look at it now and all the questions there I had were already addressed :+1:

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Is there anything else needed in order to merge this PR?

**Comment by rafaelrinaldi** [comment]
I've done a fresh Fish install this morning and used this installer. Everything seems to be working well :+1:

**Pull request merged**
