### PR TITLE
switch to andreiborisov docker image to test against version up to 3.1.2

### PR DESCRIPTION
**Pull request by edouard-lopez**
As [oh-my-fish/dockerfiles](https://github.com/oh-my-fish/dockerfiles) repo is stuck to `3.0.0` without activity for the last 1 and a half, I'm switching to @andreiborisov [docker images](https://github.com/andreiborisov/docker-fish) so we can test against versions up to `3.1.2` 

* [x] clean our dockerfile from redundancy with parent image
* [x] update travis files images
* [x] add new version to test in CI

### CODE REVIEW

**Comment by andreiborisov** [comment]
Hi! Are you guys still supporting fish 2? Fisher dropped support for the second version recently, so I have a choice to pull the latest supported version of Fisher for the v2-based images or drop v2 support altogether. Let me know if you still planning to use v2 images, please.

Also, I have an example of how to set up tests with GitHub Actions, if you want to ditch Travis: https://github.com/andreiborisov/fish-package
😉

**Comment by jorgebucaran** [comment]
Good idea, @andreiborisov. [This is my workflow](https://github.com/jorgebucaran/fisher/blob/main/.github/workflows/ci.yml) for fish plugins by the way.

**Comment by edouard-lopez** [comment]
@andreiborisov yep we will drop support for fish 2.x as described in [Versions-Support-Strategy](https://github.com/rafaelrinaldi/pure/wiki/Versions-Support-Strategy).

Travis CI is doing the job so nothing to fix but I'm open to switch (out of curiosity as I'm still unfamiliar with github CI)

**Comment by andreiborisov** [comment]
I'm dropping v2 support too then🙌

> I'm open to switch (out of curiosity as I'm still unfamiliar with github CI)

It would be as easy as adding [`docker-compose.yml`](https://github.com/andreiborisov/fish-plugin/blob/main/docker-compose.test.yml) for testing and [a GitHub workflow config itself](https://github.com/andreiborisov/fish-plugin/blob/main/.github/workflows/run-tests.yaml), which is also quite simple and straightforward.

The only thing you'd need to tweak is to change the path to test files here: https://github.com/andreiborisov/fish-plugin/blob/89550024d7bf8438f9d9d02040f0d75da03d2760/docker-compose.test.yml#L6 and remove v2 fish versions from both files.

**Comment by edouard-lopez** [comment]
Thanks I will have a look shortly, TravisCI is way too slow! :angry:

**Pull request merged**
