### PR TITLE
Prompt should be customizable

### PR DESCRIPTION
**Pull request by Shougo**
Thank you for your plugin!

I have implemented the customize feature.

### CODE REVIEW

**Comment by edouard-lopez** [comment]
Thanks, could you write a function to do that? It would greatly improve readability and maintainability.

**Comment by Shougo** [comment]
OK.  I will do it.

Note: I think the prompt colors should be customizable too.

**Comment by rafaelrinaldi** [comment]
@Shougo Thanks for your PR! It's been a while since I wanted to do this (see #2), I'm glad someone did! I'm 👍 with have custom color palete, feel free to give it a shot.

**Comment by Shougo** [comment]
* Add `__set_default` function
* Colors can be customizable
* Better global variable names

**Comment by edouard-lopez** [comment]
Thanks, good idea to namespace the variables with `pure_` prefix.

**Comment by Shougo** [comment]
@rafaelrinaldi This PR can be merged?

**Comment by rafaelrinaldi** [comment]
@Shougo Would love if you could also document how to customize colors, so users are aware of this feature.

Thoughts @edouard-lopez, @oranja?

**Comment by oranja** [comment]
What's simpler than just documenting it in your README?
For OMF users - it will appear in OMF's gallery of themes. Perhaps at some point we will show short descriptions for users when installing new packages, and that could be used to hint at customization options. (Can't promise though)

**Comment by Shougo** [comment]
OK.  I will add README description.

**Comment by Shougo** [comment]
I have added the examples in README.

**Comment by edouard-lopez** [comment]
The `__set_default` function is not namespaced, it would be better to add a `pure_` prefix like you did to otthers functions. This is an obvious name for a function which has a high probability of being in conflict with already existing one.

Also why the readme use `set` instead of `__set_default` function?

**Comment by Shougo** [comment]
> The __set_default function is not namespaced, it would be better to add a pure_ prefix like you did to otthers functions. 

OK.

> Also why the readme use set instead of __set_default function?

Because it is not for the users.

**Comment by Shougo** [comment]
I have changed the function name.

**Comment by rafaelrinaldi** [comment]
@Shougo Thanks man. It looks really good! Any other comments @edouard-lopez @oranja?

**Comment by Shougo** [comment]
Thank you!

**Comment by oranja** [comment]
Looks great. This was requested a long time ago so kudos to @Shougo for making it happen!

Only thing I'd add is a single line to the _readme_ that explains that the customization can be made permanent by appending the `set` lines to the end of **~/.config/fish/config.fish**.

**Comment by rafaelrinaldi** [comment]
@oranja Can you give it a shot? 😏

**Pull request merged**
