### PR TITLE
refactor: use conf.d for handling the fish_prompt event

### PR DESCRIPTION
**Pull request by jorgebucaran**
This PR fixes a problem when uninstalling pure where the function `pre_prompt` is still defined (can't be erased because it's not in its own fish file—event handlers should go in conf.d), which continues to handle `fish_prompt` events. At this point in time, pure's helper functions have been erased. 

```console
fish: Unknown command '__parse_current_folder'
~/.config/fish/functions/fish_prompt.fish (line 1): 
__parse_current_folder
^
in command substitution
	called on line 101 of file ~/.config/fish/functions/fish_prompt.fish

in function 'pre_prompt'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

fish: Unknown command '__parse_git_branch'
~/.config/fish/functions/fish_prompt.fish (line 1): 
__parse_git_branch
^
in command substitution
	called on line 144 of file ~/.config/fish/functions/fish_prompt.fish

in function 'pre_prompt'
	called on standard input

in event handler: handler for generic event 'fish_prompt'
```

Additionally, it moves the `installer.md` and `installer.fish` files to their own `tools/` directory closing #83.

cc @rafaelrinaldi @edouard-lopez

### CODE REVIEW

**Comment by jorgebucaran** [comment]
@rafaelrinaldi @edouard-lopez Is there anything still to do to get this merged? Can I help in some way?

**Comment by jorgebucaran** [comment]
@edouard-lopez Yes, indeed. I’ve just finished rewriting Fisher and Fishtape is coming up next.

**Comment by edouard-lopez** [comment]
I fixed the tests with 84999c9dc877dc4ee5b25c4e47b763d0ce9091c2

**Comment by edouard-lopez** [comment]
@jorgebucaran the CI still fails, it doesn't run on the latest version of `master`, could you bump your PR?

**Comment by jorgebucaran** [comment]
@edouard-lopez Rebased.

**Comment by edouard-lopez** [comment]
@jorgebucaran Cool, now tests fail in a meaningful way:

```
source: Error encountered while sourcing file '/home/travis/build/rafaelrinaldi/pure/tests/../installer.fish':
source: No such file or directory
```

First line of `tests/installer.test.fish` need to be updated to:

    source $DIRNAME/../tools/installer.fish

**Pull request merged**
