### PR TITLE
Fix for #250

### PR DESCRIPTION
**Pull request by mattmc3**
Source _pure_uninstall.fish using relative paths in the pure project rather than assuming pure is in $__fish_config_dir

### CODE REVIEW

**Review by jorgebucaran — CHANGES_REQUESTED** [review]
Much better would be to bring back the event handler to this file like [this](https://github.com/rafaelrinaldi/pure/pull/243/files#diff-321d787f568999c1841f877b33c607c831fd123719c2e8d9582d4e3f71c93c34R76-R80).

**Comment by mattmc3** [comment]
@jorgebucaran - If you are suggesting just removing the function file and putting that function in conf.d/_pure_init.fish, I think that's a solid idea. Pushed a new commit to the PR.

**Review by jorgebucaran — APPROVED** [review]
LGTM

**Comment by edouard-lopez** [comment]
Thanks @mattmc3 for working out the issue (and @jorgebucaran for helping out)

**Comment by edouard-lopez** [comment]
fixes #250

**Pull request merged**
